name: 'Custom Caddy Docker builder'
description: 'Build a Caddy docker container'
author: 'Luke Thomas'

inputs:
  modules:
    description: |
      A list of links to caddy modules

runs:
  using: "composite"
  steps: 
    - name: Output modules
      run: echo $INPUT_MODULES
      shell: bash
      env:
        INPUT_MODULES: ${{ inputs.modules }}
